# wpctl status and wpctl inspect <sink-id> and use node.name
zones:
- name: Kitchen
  id: alsa_output.usb-Antlion_Audio_Antlion_USB_adapter_20180707-00.analog-stereo
- name: Living Room
  id: alsa_output.usb-Antlion_Audio_Antlion_USB_adapter_20180707-00.2.analog-stereo
- name: Dining Room
  id: alsa_output.usb-Antlion_Audio_Antlion_USB_adapter_20180707-00.3.analog-stereo
# - name: Bathroom
#   id: alsa_output.usb-Antlion_Audio_Antlion_USB_adapter_20180707-00.4.analog-stereo

default_sink: SoundboxOutput
sinks:
- SoundboxOutput

webserver:
  ip: "0.0.0.0"
  port: "8090"
